name: 'Build HyperDLNA'
on:
  push:
  schedule:
    - cron: '25 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Github CLI      
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build APK
        run: bash ./gradlew --no-daemon assembleDebug --stacktrace
      - name: Upload apk to upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: 'app/build/outputs/apk/debug/app-debug.apk'
      - name: Publish Releases
        run: |
          gh config set prompt disabled
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} gh release create "$(date +%s)" -t "$(date +%s)" -p app/build/outputs/apk/debug/app-debug.apk
